USE university_timetabling;

INSERT INTO faculties(faculty_id,faculty_code,faculty_name) VALUES (1,'FHS','Faculty of Health Sciences');
INSERT INTO faculties(faculty_id,faculty_code,faculty_name) VALUES (2,'FST','Faculty of Science And Technology');
INSERT INTO faculties(faculty_id,faculty_code,faculty_name) VALUES (3,'FVM','Faculty of Veterinary Medicine');
INSERT INTO faculties(faculty_id,faculty_code,faculty_name) VALUES (4,'FBMS','Faculty of Business and Management Sciences');

INSERT INTO departments(dept_id,dept_code,dept_name,faculty_id) VALUES (1,'I18','computer science',2);
INSERT INTO departments(dept_id,dept_code,dept_name,faculty_id) VALUES (2,'I20','mathematics',2);
INSERT INTO departments(dept_id,dept_code,dept_name,faculty_id) VALUES (3,'B17','commerce',4);

INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (1,'1st Year Computer Lab',120,'LAB',1,1);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (2,'2nd Year Computer Lab',120,'LAB',1,1);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (3,'3rd Year Computer Lab',120,'LAB',1,1);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (4,'4th Year Computer Lab',120,'LAB',1,1);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (5,'SCI Room 100',120,'SLT',1,1);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (6,'SCI Room 200',120,'SLT',1,1);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (7,'SCI Room 300',120,'SLT',1,1);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (8,'SCI Room 400',120,'SLT',1,1);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (9,'DS Room 100',279,'SLT',1,2);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (10,'DS Room 200',135,'LT',1,2);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (11,'DS Room 300',374,'LT',1,2);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (12,'DS Room 400',94,'LT',1,2);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (13,'Bcom Room 100',230,'LT',1,3);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (14,'Bcom Room 200',104,'LT',1,3);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (15,'Bcom Room 300',495,'LT',1,3);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (16,'Bcom Room 400',193,'SLT',1,3);
INSERT INTO rooms(room_id,room_name,room_capacity,room_type,is_available,dept_id) VALUES (17,'Millenium Hall 1234',800,'HALL',1,3);

INSERT INTO room_department(room_id,dept_id) VALUES (1,1);
INSERT INTO room_department(room_id,dept_id) VALUES (2,1);
INSERT INTO room_department(room_id,dept_id) VALUES (3,1);
INSERT INTO room_department(room_id,dept_id) VALUES (4,1);
INSERT INTO room_department(room_id,dept_id) VALUES (5,1);
INSERT INTO room_department(room_id,dept_id) VALUES (6,1);
INSERT INTO room_department(room_id,dept_id) VALUES (7,1);
INSERT INTO room_department(room_id,dept_id) VALUES (8,1);
INSERT INTO room_department(room_id,dept_id) VALUES (9,2);
INSERT INTO room_department(room_id,dept_id) VALUES (10,2);
INSERT INTO room_department(room_id,dept_id) VALUES (11,2);
INSERT INTO room_department(room_id,dept_id) VALUES (12,2);
INSERT INTO room_department(room_id,dept_id) VALUES (13,3);
INSERT INTO room_department(room_id,dept_id) VALUES (14,3);
INSERT INTO room_department(room_id,dept_id) VALUES (15,3);
INSERT INTO room_department(room_id,dept_id) VALUES (16,3);
INSERT INTO room_department(room_id,dept_id) VALUES (17,1);
INSERT INTO room_department(room_id,dept_id) VALUES (17,2);
INSERT INTO room_department(room_id,dept_id) VALUES (17,3);


INSERT INTO programmes(programme_id,programme_code,programme_name,faculty_id) VALUES (1,'P15','Bachelor of Science Computer Science',2);
INSERT INTO programmes(programme_id,programme_code,programme_name,faculty_id) VALUES (2,'I17','Bachelor of Science In Data Science',2);
INSERT INTO programmes(programme_id,programme_code,programme_name,faculty_id) VALUES (3,'B22','Bachelor of Commerce(Human Resource)',4);

INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (1,100,1,1);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (2,100,2,1);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (3,100,3,1);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (4,100,4,1);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (5,100,1,2);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (6,100,2,2);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (7,100,3,2);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (8,100,1,3);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (9,100,2,3);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (10,100,3,3);
INSERT INTO program_enrollments(enrollment_id,enrollment_number,enrollment_year,program_id) VALUES (11,100,4,3);


INSERT INTO users(id,password,role,username,user_type) VALUES (1,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Justina','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (2,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Hildegaard','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (3,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Errol','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (4,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Denny','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (5,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Robby','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (6,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Priscilla','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (7,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Yuri','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (8,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Hermia','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (9,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Cesare','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (10,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Coleen','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (11,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Terese','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (12,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Sharona','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (13,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Juliane','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (14,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Romy','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (15,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Joan','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (16,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Vernen','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (17,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Terencio','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (18,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Haslett','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (19,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Hersch','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (20,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Lexine','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (21,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Nancey','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (22,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Merlina','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (23,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Betsey','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (24,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Andy','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (25,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Beverie','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (26,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Neel','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (27,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Vinita','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (28,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Rana','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (29,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Bondie','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (30,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Avram','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (31,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Susie','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (32,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Ferdinande','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (33,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Brander','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (34,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Myrilla','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (35,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Jacinda','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (36,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Avis','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (37,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Umberto','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (38,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Jesselyn','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (39,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Yettie','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (40,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Ruttger','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (41,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Lucienne','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (42,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Issi','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (43,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Garvy','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (44,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Sergent','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (45,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','INSTRUCTOR','Fannie','Instructor');
INSERT INTO users(id,password,role,username,user_type) VALUES (46,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Kyalo','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (47,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Wanyoro','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (48,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Kaseve','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (49,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Yvette','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (50,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Maurice','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (51,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Mativo','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (52,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Jeff','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (53,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Kimingi','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (54,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Mercy','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (55,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Brendah','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (56,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','STUDENT','Sandrah','Student');
INSERT INTO users(id,password,role,username,user_type) VALUES (57,'$2a$10$ynmv1/ETM9jvnXy5JWzUTO9R9r6ASAW8DWbuXqEsH2gBsS5IpgViG','ADMIN','Admin','');


INSERT INTO students(id,year,program_id,user_id) VALUES (1,1,1,46);
INSERT INTO students(id,year,program_id,user_id) VALUES (2,2,1,47);
INSERT INTO students(id,year,program_id,user_id) VALUES (3,3,1,48);
INSERT INTO students(id,year,program_id,user_id) VALUES (4,4,1,49);
INSERT INTO students(id,year,program_id,user_id) VALUES (5,1,2,50);
INSERT INTO students(id,year,program_id,user_id) VALUES (6,2,2,51);
INSERT INTO students(id,year,program_id,user_id) VALUES (7,3,2,52);
INSERT INTO students(id,year,program_id,user_id) VALUES (8,1,3,53);
INSERT INTO students(id,year,program_id,user_id) VALUES (9,2,3,54);
INSERT INTO students(id,year,program_id,user_id) VALUES (10,3,3,55);
INSERT INTO students(id,year,program_id,user_id) VALUES (11,4,3,56);


INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (1,'Justina','Rattray',1,1);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (2,'Hildegaard','Daintrey',1,2);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (3,'Errol','Belfelt',1,3);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (4,'Denny','Huyton',1,4);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (5,'Robby','Jacobovitch',1,5);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (6,'Priscilla','Bulley',1,6);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (7,'Yuri','Heisler',1,7);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (8,'Hermia','Raynard',1,8);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (9,'Cesare','Booth-Jarvis',1,9);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (10,'Coleen','McClifferty',1,10);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (11,'Terese','Murtagh',1,11);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (12,'Sharona','Kemwall',1,12);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (13,'Juliane','Waddilow',1,13);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (14,'Romy','Lowdham',1,14);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (15,'Joan','Baseley',1,15);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (16,'Vernen','Prandini',1,16);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (17,'Terencio','Skewes',1,17);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (18,'Haslett','Borrows',2,18);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (19,'Hersch','Feragh',2,19);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (20,'Lexine','Shutle',2,20);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (21,'Nancey','Fierro',2,21);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (22,'Merlina','Threadgall',2,22);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (23,'Betsey','Gatley',2,23);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (24,'Andy','Grigs',2,24);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (25,'Beverie','Guitt',2,25);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (26,'Neel','Romaine',2,26);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (27,'Vinita','Thulborn',2,27);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (28,'Rana','Viccary',2,28);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (29,'Bondie','Pryell',2,29);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (30,'Avram','Lademann',2,30);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (31,'Susie','Eastgate',3,31);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (32,'Ferdinande','Piele',3,32);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (33,'Brander','Daltrey',3,33);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (34,'Myrilla','Croxon',3,34);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (35,'Jacinda','Edgin',3,35);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (36,'Avis','Dosedale',3,36);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (37,'Umberto','Fourcade',3,37);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (38,'Jesselyn','Haggart',3,38);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (39,'Yettie','Eglese',3,39);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (40,'Ruttger','Castellini',3,40);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (41,'Lucienne','Howels',3,41);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (42,'Issi','Bracer',3,42);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (43,'Garvy','Livezley',3,43);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (44,'Sergent','Dixon',3,44);
INSERT INTO instructors(instructor_id,first_name,last_name,dept_id,user_id) VALUES (45,'Fannie','Ayers',3,45);

INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (1,'CSC111','Introduction to Computer Systems',1,1,NULL,1,1,1,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (2,'CSC112','Introduction to Programming',1,1,NULL,1,1,2,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (3,'CSC113','Discrete Mathematics',1,1,'SLT',1,1,3,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (4,'CSC115','Programming Lab �',1,1,'LAB',1,1,4,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (5,'CSC126','Physics for Computing Systems',1,1,NULL,1,1,5,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (6,'CCS001','Communication Skills',1,1,'HALL',1,1,6,1);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (7,'CCS009','Elements of Economics�',1,1,NULL,1,1,7,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (8,'CSC122�','Database Systems',1,2,NULL,1,1,8,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (9,'CSC123','Data Communications',1,2,NULL,1,1,9,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (10,'�CSC125','Linear Algebra�',1,2,NULL,1,1,10,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (11,'CSC127','Object Oriented Programming',1,2,NULL,1,1,11,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (12,'CSC211','�Data Structures and Algorithms',1,2,NULL,1,1,12,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (13,'CSC214','Digital Electronics �',1,2,NULL,1,1,13,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (14,'CCS010','HIV/AIDS �',1,2,NULL,1,1,14,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (15,'CSC114','Differential and Integral Calculus',2,1,NULL,1,1,15,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (16,'CSC212�','Systems Analysis and Design',2,1,NULL,1,1,16,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (17,'CSC213�','Computer Architecture',2,1,NULL,1,1,17,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (18,'CSC217�','Knowledge-based Systems & Programming �',2,1,NULL,1,1,1,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (19,'CSC223�','Operating Systems �',2,1,NULL,1,1,2,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (20,'CSC224�','Software Engineering',2,1,NULL,1,1,3,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (21,'CSC225�','�Computer Networks �',2,1,NULL,1,1,4,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (22,'CSC124','Probability and Statistics',2,2,NULL,1,1,5,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (23,'CSC216�','Assembly Language Programming',2,2,NULL,1,1,6,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (24,'CSC222�','Automata Theory',2,2,NULL,1,1,7,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (25,'CSC227�','Programming Project�',2,2,NULL,1,1,8,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (26,'CSC228�','Web and Services Programming �',2,2,NULL,1,1,9,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (27,'CSC229�','Machine Learning Algorithms & Programming�',2,2,NULL,1,1,10,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (28,'CSC313�','Foundations of Human Computer Interaction',2,2,NULL,1,1,11,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (29,'CSC311�','Analysis and Design of Algorithms',3,1,NULL,1,1,12,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (30,'CSC314�','Computer Graphics �',3,1,NULL,1,1,13,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (31,'CSC315�','Distributed Systems',3,1,NULL,1,1,14,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (32,'CSC316�','Intro to Organizations and Management �',3,1,NULL,1,1,15,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (33,'CSC317�','Artificial Intelligence Applications',3,1,NULL,1,1,16,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (34,'CSC318�','Network Design Implementation and Management',3,1,NULL,1,1,17,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (35,'CSC319�','Innovation & Entrepreneurship',3,1,NULL,1,1,1,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (36,'CSC321�','ICT Project Management',3,2,NULL,1,1,2,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (37,'CSC322�','Network and Distributed Programming',3,2,NULL,1,1,3,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (38,'CSC326�','Compiler Construction',3,2,NULL,1,1,4,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (39,'CSC327�','Embedded Systems & Mobile Programming',3,2,NULL,1,1,5,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (40,'CSC328�','Business Intelligence & Analytics',3,2,NULL,1,1,6,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (41,'CSC411�','Computer Network Security',3,2,NULL,1,1,7,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (42,'CSC414','ICTs and Society�',4,1,NULL,1,1,8,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (43,'CSC417�','Information Systems and Organizations',4,1,NULL,1,1,9,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (44,'CSC418�','Emerging Technologies Bootcamps',4,1,NULL,1,1,10,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (45,'CSC451�','Distributed Databases�',4,1,NULL,1,1,11,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (46,'CSC481�','Computer Games Programming',4,1,NULL,1,1,12,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (47,'CSC416�','Computer Systems Project �',4,1,NULL,1,1,13,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (48,'CSC416','Computer Systems Project',4,2,NULL,1,1,14,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (49,'CSC434�','Cloud Computing and Services',4,2,NULL,1,1,15,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (50,'CSC452�','Information Systems Control Audit �',4,2,NULL,1,1,16,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (51,'CSC455�','Information for Emerging Online Solutions�',4,2,NULL,1,1,17,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (52,'SMA3101','Basic Mathematics',1,1,NULL,2,2,18,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (53,'SMA3103','Calculus I',1,1,NULL,2,2,19,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (54,'SMA3105','Geometry I',1,1,NULL,2,2,20,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (55,'STA3101','Introduction to Probability and Statistics',1,1,NULL,2,2,21,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (56,'SCS3101','Introduction to Computer Systems',1,1,NULL,2,2,22,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (57,'SCS3103','Introduction to Programming',1,1,NULL,2,2,23,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (58,'SMA3104','Calculus II',1,2,NULL,2,2,24,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (59,'SMA3116','Geometry II',1,2,NULL,2,2,25,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (60,'SMA3108','Discrete Mathematics I',1,2,NULL,2,2,26,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (61,'SDS3102','Foundations of Data Science',1,2,NULL,2,2,27,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (62,'CCS010','HIV/AIDS �',1,2,NULL,2,2,28,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (63,'SMA3201','Advanced Calculus',2,1,NULL,2,2,29,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (64,'SMA3203','Linear Algebra I',2,1,NULL,2,2,30,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (65,'SMA3251','Discrete Mathematics II',2,1,NULL,2,2,18,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (66,'STA3201','Probability and Statistics I',2,1,NULL,2,2,19,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (67,'SDS3201','Database Systems',2,1,NULL,2,2,20,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (68,'SDS3203','Data Structures and Algorithms',2,2,NULL,2,2,21,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (69,'SMA3204','Linear Algebra II',2,2,NULL,2,2,22,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (70,'SMA3206','Introduction to Analysis',2,2,NULL,2,2,23,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (71,'SMA3208','Ordinary Differential Equations I',2,2,NULL,2,2,24,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (72,'STA3202','Statistical Inference I',2,2,NULL,2,2,25,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (73,'STA3222','Time Series Analysis',2,2,NULL,2,2,26,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (74,'SDS3204','Data Mining and Visualization',2,1,NULL,2,2,27,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (75,'STA3301','Probability and Statistics II',3,1,NULL,2,2,28,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (76,'SMA3351','Optimization Methods',3,1,NULL,2,2,29,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (77,'SDS3301','Artificial Intelligence',3,1,NULL,2,2,30,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (78,'SDS3303','Systems Analysis and Design',3,1,NULL,2,2,18,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (79,'SDS3311','Numerical Methods and Convex Optimisation',3,2,NULL,2,2,19,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (80,'STA3302','Linear Modeling',3,2,NULL,2,2,20,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (81,'STA3308','Sample Survey Methods',3,2,NULL,2,2,21,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (82,'STA3318','Statistical Inference II',3,2,NULL,2,2,22,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (83,'SDS3304','Software Engineering',3,2,NULL,2,2,23,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (84,'SDS3306','Machine Learning',3,2,NULL,2,2,24,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (85,'CCS001','Communication Skills',1,1,NULL,3,3,31,1);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (86,'ICT1101','Introduction to Information Systems',1,1,NULL,3,3,32,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (87,'ACC1101','Introduction to Accounting I',1,1,NULL,3,3,33,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (88,'BAM1101','Business Studies',1,1,NULL,3,3,34,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (89,'BAM1102','Principles of Management',1,1,NULL,3,3,35,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (90,'MAT1102','Management Mathematics I',1,1,NULL,3,3,36,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (91,'CUU002','Information Literacy',1,1,NULL,3,3,37,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (92,'CUU0001','Health Awareness & Life Skills',1,2,NULL,3,3,38,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (93,'BAM1204','Business Law I',1,2,NULL,3,3,39,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (94,'BAM1205','Development Sudies and Ethics',1,2,NULL,3,3,40,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (95,'ACC1202','Introduction to Accounting II',1,2,NULL,3,3,41,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (96,'ECO11201','Introduction to Macroeconomics',1,2,NULL,3,3,42,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (97,'MKT1101','Principles of Marketing',1,2,NULL,3,3,43,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (98,'MAT1203','Management Mathematics II',1,2,NULL,3,3,44,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (99,'ACC1303','Introduction to Taxation',2,1,NULL,3,3,45,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (100,'ACC1304','Intermediate Accounting I',2,1,NULL,3,3,31,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (101,'FIN1301','Business Finance',2,1,NULL,3,3,32,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (102,'STA1305','Business Statistics I',2,1,NULL,3,3,33,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (103,'ECO1302','Introduction to Macroeconomics',2,1,NULL,3,3,34,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (104,'HRM1302','Introduction to Human Resource Management',2,1,NULL,3,3,35,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (105,'ICT2104','E-Commerce',2,2,NULL,3,3,36,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (106,'ACC2101','Introduction to Cost Accounting',2,2,NULL,3,3,37,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (107,'FIN2101','Insurance and Risk Management',2,2,NULL,3,3,38,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (108,'STA2101','Business Statistics II',2,2,NULL,3,3,39,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (109,'HRM2102','Organization Behavior',2,2,NULL,3,3,40,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (110,'FIN 2102','Financial Management',2,2,NULL,3,3,41,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (111,'BAM2201','Total Quality Management',3,1,NULL,3,3,42,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (112,'BAM2202','Company Law',3,1,NULL,3,3,43,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (113,'BAM2204','Strategic Management',3,1,NULL,3,3,44,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (114,'BAM2205','Project Management',3,1,NULL,3,3,45,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (115,'ICT2203','Computer Application Software',3,1,NULL,3,3,31,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (116,'BAM2206','Career Management',3,1,NULL,3,3,32,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (117,'ENT2306','Entreprenuership',3,2,NULL,3,3,33,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (118,'BAM2313','International Relations',3,2,NULL,3,3,34,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (119,'BAM2314','International Business Strategy',3,2,NULL,3,3,35,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (120,'HRM2309','Compenstation and Reward Management',3,2,NULL,3,3,36,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (121,'HRM2310','Industrial Safety and Health',3,2,NULL,3,3,37,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (122,'HRM2311','Training and Development',3,2,NULL,3,3,38,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (123,'HRM3118','Labour Law & Economics',4,1,NULL,3,3,39,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (124,'HRM3108','Human Resource Planning',4,1,NULL,3,3,40,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (125,'HRM3123','Strategic Human Resource Management',4,1,NULL,3,3,41,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (126,'CFU3100','Research Methodology',4,1,NULL,3,3,42,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (127,'HRM3119','Human Resource Information Systems',4,1,NULL,3,3,43,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (128,'HRM3221','Global HRM',4,2,NULL,3,3,44,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (129,'HRM3215','Perfomance-Based Management',4,2,NULL,3,3,45,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (130,'CFU3204','Research Project',4,2,NULL,3,3,31,0);
INSERT INTO courses(course_id,course_code,course_name,year,semester,room_spec,programme_id,dept_id,instructor_id,common_id) VALUES (131,'HRM3211','Employee relations',4,2,NULL,3,3,32,0);


INSERT INTO time_slots(id,day,start_time,end_time) VALUES (1,'Monday','09:00:00','10:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (2,'Tuesday','09:00:00','10:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (3,'Wednesday','09:00:00','10:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (4,'Thursday','09:00:00','10:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (5,'Friday','09:00:00','10:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (6,'Monday','11:15:00','13:00:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (7,'Tuesday','11:15:00','13:00:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (8,'Wednesday','11:15:00','13:00:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (9,'Thursday','11:15:00','13:00:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (10,'Friday','11:15:00','13:00:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (11,'Monday','14:00:00','15:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (12,'Tuesday','14:00:00','15:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (13,'Wednesday','14:00:00','15:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (14,'Thursday','14:00:00','15:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (15,'Friday','14:00:00','15:45:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (16,'Monday','15:45:00','17:30:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (17,'Tuesday','15:45:00','17:30:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (18,'Wednesday','15:45:00','17:30:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (19,'Thursday','15:45:00','17:30:00');
INSERT INTO time_slots(id,day,start_time,end_time) VALUES (20,'Friday','15:45:00','17:30:00');



INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (1,2,1);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (2,2,2);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (3,2,3);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (4,2,4);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (5,2,5);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (6,2,6);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (7,2,7);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (8,2,8);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (9,2,9);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (10,2,10);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (11,2,11);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (12,2,12);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (13,2,13);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (14,1,14);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (15,2,15);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (16,2,16);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (17,2,17);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (18,2,18);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (19,2,19);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (20,2,20);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (21,2,21);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (22,2,22);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (23,2,23);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (24,2,24);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (25,2,25);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (26,2,26);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (27,2,27);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (28,2,28);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (29,2,29);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (30,2,30);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (31,2,31);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (32,2,32);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (33,2,33);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (34,2,34);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (35,2,35);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (36,2,36);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (37,2,37);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (38,2,38);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (39,2,39);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (40,2,40);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (41,2,41);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (42,2,42);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (43,2,43);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (44,2,44);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (45,2,45);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (46,4,46);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (47,4,47);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (48,2,48);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (49,2,49);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (50,2,50);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (51,2,51);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (52,2,52);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (53,2,53);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (54,2,54);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (55,2,55);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (56,2,56);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (57,2,57);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (58,2,58);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (59,2,59);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (60,2,60);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (61,2,61);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (62,1,62);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (63,2,63);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (64,2,64);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (65,2,65);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (66,2,66);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (67,2,67);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (68,2,68);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (69,2,69);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (70,2,70);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (71,2,71);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (72,2,72);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (73,2,73);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (74,2,74);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (75,2,75);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (76,2,76);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (77,2,77);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (78,2,78);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (79,2,79);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (80,2,80);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (81,2,81);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (82,2,82);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (83,2,83);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (84,1,84);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (85,2,85);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (86,2,86);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (87,2,87);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (88,2,88);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (89,2,89);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (90,2,90);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (91,2,91);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (92,2,92);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (93,2,93);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (94,2,94);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (95,2,95);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (96,2,96);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (97,2,97);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (98,2,98);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (99,2,99);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (100,2,100);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (101,2,101);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (102,2,102);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (103,2,103);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (104,2,104);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (105,2,105);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (106,2,106);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (107,2,107);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (108,2,108);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (109,2,109);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (110,2,110);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (111,2,111);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (112,2,112);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (113,2,113);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (114,2,114);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (115,2,115);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (116,2,116);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (117,2,117);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (118,2,118);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (119,2,119);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (120,2,120);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (121,2,121);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (122,2,122);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (123,2,123);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (124,2,124);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (125,2,125);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (126,2,126);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (127,2,127);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (128,2,128);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (129,2,129);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (130,4,130);
INSERT INTO sections(section_id,number_of_classes,course_id) VALUES (131,2,131);

INSERT INTO instructor_preferences(instructor_id,timeslot_id) VALUES (8,7);
INSERT INTO instructor_preferences(instructor_id,timeslot_id) VALUES (8,8);